-- Generated from generator/demo_specs/aws-thailand-automotive-ev-battery.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-automotive-ev-battery
-- This is the schema that is actually deployed for THAILAND_AUTOMOTIVE_EV_BATTERY.

-- Alerts fire on the bottom tail of Battery Yield
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_BATTERY_YIELD) AS T
  FROM RAW.CELL_TELEMETRY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_BATTERY_YIELD <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_BATTERY_YIELD), 2) AS AVG_BATTERY_YIELD,
  ROUND(AVG(f.KPI_AVG_IMPEDANCE), 2) AS AVG_IMPEDANCE,
  ROUND(AVG(f.KPI_CELL_DEFECT_RATE), 2) AS AVG_CELL_DEFECT_RATE,
  ROUND(AVG(f.KPI_FORMATION_EFFICIENCY), 2) AS AVG_FORMATION_EFFICIENCY
FROM RAW.CELL_TELEMETRY f
JOIN RAW.GIGAFACTORIES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_BATTERY_YIELD), 2) AS AVG_BATTERY_YIELD,
  ROUND(AVG(f.KPI_AVG_IMPEDANCE), 2) AS AVG_IMPEDANCE,
  ROUND(AVG(f.KPI_CELL_DEFECT_RATE), 2) AS AVG_CELL_DEFECT_RATE,
  ROUND(AVG(f.KPI_FORMATION_EFFICIENCY), 2) AS AVG_FORMATION_EFFICIENCY
FROM RAW.CELL_TELEMETRY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_BATTERY_YIELD) AS KPI_BATTERY_YIELD, AVG(KPI_CELL_DEFECT_RATE) AS KPI_CELL_DEFECT_RATE, AVG(KPI_AVG_IMPEDANCE) AS KPI_AVG_IMPEDANCE, AVG(KPI_FORMATION_EFFICIENCY) AS KPI_FORMATION_EFFICIENCY FROM RAW.CELL_TELEMETRY),
     en AS (SELECT SUM(KPI_THERMAL_EVENTS_MTD) AS KPI_THERMAL_EVENTS_MTD, SUM(KPI_PACKS_PRODUCED) AS KPI_PACKS_PRODUCED, SUM(KPI_CYCLE_LIFE_PRED) AS KPI_CYCLE_LIFE_PRED FROM RAW.GIGAFACTORIES)
  SELECT 1 AS SORT_ORDER, 'Battery Yield' AS TITLE, KPI_BATTERY_YIELD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BATTERY_YIELD), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Cell Defect Rate' AS TITLE, KPI_CELL_DEFECT_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CELL_DEFECT_RATE), 2) AS DECIMAL(38,2))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Thermal Events (MTD)' AS TITLE, KPI_THERMAL_EVENTS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_THERMAL_EVENTS_MTD)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Packs Produced' AS TITLE, KPI_PACKS_PRODUCED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_PACKS_PRODUCED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Impedance' AS TITLE, KPI_AVG_IMPEDANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_IMPEDANCE), 1) AS DECIMAL(38,1))) || ' ' || 'mΩ' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Formation Efficiency' AS TITLE, KPI_FORMATION_EFFICIENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FORMATION_EFFICIENCY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cycle Life Pred.' AS TITLE, KPI_CYCLE_LIFE_PRED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_CYCLE_LIFE_PRED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
