-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for EV Battery Production Analytics
-- ============================================================================
USE DATABASE EV_BATTERY_PROD;
USE SCHEMA ML;

-- ML.FORECAST: BATTERY_YIELD_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.BATTERY_YIELD_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.BATTERY_YIELD_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.BATTERY_YIELD_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CELL_QUALITY_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CELL_QUALITY_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CELL_HEALTH_SCORES'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CELL_QUALITY_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.CELL_QUALITY_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CELL_HEALTH_SCORES'), SERIES_COLNAME => 'LINE_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

