-- ============================================================================
-- 99_RESET.SQL — Reset EV Battery Production Analytics to clean demo state
-- ============================================================================
USE DATABASE EV_BATTERY_PROD;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_QUALITY_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.LINE_YIELD_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.CELL_HEALTH_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.MATERIAL_QUALITY_TRENDS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM EV_BATTERY_PROD.RAW.CELL_BATCHES → 8000
-- SELECT COUNT(*) FROM EV_BATTERY_PROD.RAW.CELL_TELEMETRY → 600000
-- SELECT COUNT(DISTINCT LINE_ID) FROM EV_BATTERY_PROD.CURATED.LINE_YIELD_SUMMARY WHERE YIELD_STATUS = 'CRITICAL' → 3

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_QUALITY_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
